name 'data_file'
version '0.1.1'
maintainer 'Maciej Pasternacki'
maintainer_email 'maciej@3ofcoins.net'
license 'MIT'
description 'Resources to create JSON and YAML files'
long_description 'Resources to create JSON and YAML files'
issues_url 'https://github.com/3ofcoins/chef-cookbook-data_file/issues'
source_url 'https://github.com/3ofcoins/chef-cookbook-data_file/'
